/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppWorkspaceRouteRouteImport } from './routes/_authenticated/app/_workspace/route'
import { Route as AuthForgotPasswordSentRouteImport } from './routes/auth/forgot-password.sent'
import { Route as AuthResetPasswordSuccessRouteImport } from './routes/auth/reset-password.success'
import { Route as AuthenticatedAppWorkspaceApprovalsIndexRouteImport } from './routes/_authenticated/app/_workspace/approvals/index'
import { Route as AuthenticatedAppWorkspaceDashboardIndexRouteImport } from './routes/_authenticated/app/_workspace/dashboard/index'
import { Route as AuthenticatedAppWorkspaceIntegrationsIndexRouteImport } from './routes/_authenticated/app/_workspace/integrations/index'
import { Route as AuthenticatedAppWorkspaceProjectsIndexRouteImport } from './routes/_authenticated/app/_workspace/projects/index'
import { Route as AuthenticatedAppWorkspaceRunsIndexRouteImport } from './routes/_authenticated/app/_workspace/runs/index'
import { Route as AuthenticatedAppWorkspaceSettingsIndexRouteImport } from './routes/_authenticated/app/_workspace/settings/index'
import { Route as AuthenticatedAppWorkspaceTasksIndexRouteImport } from './routes/_authenticated/app/_workspace/tasks/index'
import { Route as AuthenticatedAppWorkspaceTasksTaskIdRouteImport } from './routes/_authenticated/app/_workspace/tasks/$taskId'
import { Route as AuthenticatedAppWorkspaceTasksNewRouteImport } from './routes/_authenticated/app/_workspace/tasks/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppWorkspaceRouteRoute =
  AuthenticatedAppWorkspaceRouteRouteImport.update({
    id: '/_workspace',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthForgotPasswordSentRoute = AuthForgotPasswordSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => AuthForgotPasswordRoute,
} as any)
const AuthResetPasswordSuccessRoute =
  AuthResetPasswordSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => AuthResetPasswordRoute,
  } as any)
const AuthenticatedAppWorkspaceApprovalsIndexRoute =
  AuthenticatedAppWorkspaceApprovalsIndexRouteImport.update({
    id: '/approvals/',
    path: '/approvals/',
    getParentRoute: () => AuthenticatedAppWorkspaceRouteRoute,
  } as any)
const AuthenticatedAppWorkspaceDashboardIndexRoute =
  AuthenticatedAppWorkspaceDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedAppWorkspaceRouteRoute,
  } as any)
const AuthenticatedAppWorkspaceIntegrationsIndexRoute =
  AuthenticatedAppWorkspaceIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AuthenticatedAppWorkspaceRouteRoute,
  } as any)
const AuthenticatedAppWorkspaceProjectsIndexRoute =
  AuthenticatedAppWorkspaceProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedAppWorkspaceRouteRoute,
  } as any)
const AuthenticatedAppWorkspaceRunsIndexRoute =
  AuthenticatedAppWorkspaceRunsIndexRouteImport.update({
    id: '/runs/',
    path: '/runs/',
    getParentRoute: () => AuthenticatedAppWorkspaceRouteRoute,
  } as any)
const AuthenticatedAppWorkspaceSettingsIndexRoute =
  AuthenticatedAppWorkspaceSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedAppWorkspaceRouteRoute,
  } as any)
const AuthenticatedAppWorkspaceTasksIndexRoute =
  AuthenticatedAppWorkspaceTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AuthenticatedAppWorkspaceRouteRoute,
  } as any)
const AuthenticatedAppWorkspaceTasksTaskIdRoute =
  AuthenticatedAppWorkspaceTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AuthenticatedAppWorkspaceRouteRoute,
  } as any)
const AuthenticatedAppWorkspaceTasksNewRoute =
  AuthenticatedAppWorkspaceTasksNewRouteImport.update({
    id: '/tasks/new',
    path: '/tasks/new',
    getParentRoute: () => AuthenticatedAppWorkspaceRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRouteWithChildren
  '/auth/reset-password': typeof AuthResetPasswordRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/': typeof AuthIndexRoute
  '/auth/forgot-password/sent': typeof AuthForgotPasswordSentRoute
  '/auth/reset-password/success': typeof AuthResetPasswordSuccessRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/tasks/$taskId': typeof AuthenticatedAppWorkspaceTasksTaskIdRoute
  '/app/tasks/new': typeof AuthenticatedAppWorkspaceTasksNewRoute
  '/app/approvals/': typeof AuthenticatedAppWorkspaceApprovalsIndexRoute
  '/app/dashboard/': typeof AuthenticatedAppWorkspaceDashboardIndexRoute
  '/app/integrations/': typeof AuthenticatedAppWorkspaceIntegrationsIndexRoute
  '/app/projects/': typeof AuthenticatedAppWorkspaceProjectsIndexRoute
  '/app/runs/': typeof AuthenticatedAppWorkspaceRunsIndexRoute
  '/app/settings/': typeof AuthenticatedAppWorkspaceSettingsIndexRoute
  '/app/tasks/': typeof AuthenticatedAppWorkspaceTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRouteWithChildren
  '/auth/reset-password': typeof AuthResetPasswordRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth': typeof AuthIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/auth/forgot-password/sent': typeof AuthForgotPasswordSentRoute
  '/auth/reset-password/success': typeof AuthResetPasswordSuccessRoute
  '/app/tasks/$taskId': typeof AuthenticatedAppWorkspaceTasksTaskIdRoute
  '/app/tasks/new': typeof AuthenticatedAppWorkspaceTasksNewRoute
  '/app/approvals': typeof AuthenticatedAppWorkspaceApprovalsIndexRoute
  '/app/dashboard': typeof AuthenticatedAppWorkspaceDashboardIndexRoute
  '/app/integrations': typeof AuthenticatedAppWorkspaceIntegrationsIndexRoute
  '/app/projects': typeof AuthenticatedAppWorkspaceProjectsIndexRoute
  '/app/runs': typeof AuthenticatedAppWorkspaceRunsIndexRoute
  '/app/settings': typeof AuthenticatedAppWorkspaceSettingsIndexRoute
  '/app/tasks': typeof AuthenticatedAppWorkspaceTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRouteWithChildren
  '/auth/reset-password': typeof AuthResetPasswordRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/app/_workspace': typeof AuthenticatedAppWorkspaceRouteRouteWithChildren
  '/auth/forgot-password/sent': typeof AuthForgotPasswordSentRoute
  '/auth/reset-password/success': typeof AuthResetPasswordSuccessRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/_workspace/tasks/$taskId': typeof AuthenticatedAppWorkspaceTasksTaskIdRoute
  '/_authenticated/app/_workspace/tasks/new': typeof AuthenticatedAppWorkspaceTasksNewRoute
  '/_authenticated/app/_workspace/approvals/': typeof AuthenticatedAppWorkspaceApprovalsIndexRoute
  '/_authenticated/app/_workspace/dashboard/': typeof AuthenticatedAppWorkspaceDashboardIndexRoute
  '/_authenticated/app/_workspace/integrations/': typeof AuthenticatedAppWorkspaceIntegrationsIndexRoute
  '/_authenticated/app/_workspace/projects/': typeof AuthenticatedAppWorkspaceProjectsIndexRoute
  '/_authenticated/app/_workspace/runs/': typeof AuthenticatedAppWorkspaceRunsIndexRoute
  '/_authenticated/app/_workspace/settings/': typeof AuthenticatedAppWorkspaceSettingsIndexRoute
  '/_authenticated/app/_workspace/tasks/': typeof AuthenticatedAppWorkspaceTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cookies'
    | '/docs'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/app'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-up'
    | '/auth/'
    | '/auth/forgot-password/sent'
    | '/auth/reset-password/success'
    | '/app/'
    | '/app/tasks/$taskId'
    | '/app/tasks/new'
    | '/app/approvals/'
    | '/app/dashboard/'
    | '/app/integrations/'
    | '/app/projects/'
    | '/app/runs/'
    | '/app/settings/'
    | '/app/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/docs'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-up'
    | '/auth'
    | '/app'
    | '/auth/forgot-password/sent'
    | '/auth/reset-password/success'
    | '/app/tasks/$taskId'
    | '/app/tasks/new'
    | '/app/approvals'
    | '/app/dashboard'
    | '/app/integrations'
    | '/app/projects'
    | '/app/runs'
    | '/app/settings'
    | '/app/tasks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cookies'
    | '/docs'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/app'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-up'
    | '/auth/'
    | '/_authenticated/app/_workspace'
    | '/auth/forgot-password/sent'
    | '/auth/reset-password/success'
    | '/_authenticated/app/'
    | '/_authenticated/app/_workspace/tasks/$taskId'
    | '/_authenticated/app/_workspace/tasks/new'
    | '/_authenticated/app/_workspace/approvals/'
    | '/_authenticated/app/_workspace/dashboard/'
    | '/_authenticated/app/_workspace/integrations/'
    | '/_authenticated/app/_workspace/projects/'
    | '/_authenticated/app/_workspace/runs/'
    | '/_authenticated/app/_workspace/settings/'
    | '/_authenticated/app/_workspace/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  DocsRoute: typeof DocsRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/_workspace': {
      id: '/_authenticated/app/_workspace'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppWorkspaceRouteRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/auth/forgot-password/sent': {
      id: '/auth/forgot-password/sent'
      path: '/sent'
      fullPath: '/auth/forgot-password/sent'
      preLoaderRoute: typeof AuthForgotPasswordSentRouteImport
      parentRoute: typeof AuthForgotPasswordRoute
    }
    '/auth/reset-password/success': {
      id: '/auth/reset-password/success'
      path: '/success'
      fullPath: '/auth/reset-password/success'
      preLoaderRoute: typeof AuthResetPasswordSuccessRouteImport
      parentRoute: typeof AuthResetPasswordRoute
    }
    '/_authenticated/app/_workspace/approvals/': {
      id: '/_authenticated/app/_workspace/approvals/'
      path: '/approvals'
      fullPath: '/app/approvals/'
      preLoaderRoute: typeof AuthenticatedAppWorkspaceApprovalsIndexRouteImport
      parentRoute: typeof AuthenticatedAppWorkspaceRouteRoute
    }
    '/_authenticated/app/_workspace/dashboard/': {
      id: '/_authenticated/app/_workspace/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AuthenticatedAppWorkspaceDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedAppWorkspaceRouteRoute
    }
    '/_authenticated/app/_workspace/integrations/': {
      id: '/_authenticated/app/_workspace/integrations/'
      path: '/integrations'
      fullPath: '/app/integrations/'
      preLoaderRoute: typeof AuthenticatedAppWorkspaceIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedAppWorkspaceRouteRoute
    }
    '/_authenticated/app/_workspace/projects/': {
      id: '/_authenticated/app/_workspace/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AuthenticatedAppWorkspaceProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedAppWorkspaceRouteRoute
    }
    '/_authenticated/app/_workspace/runs/': {
      id: '/_authenticated/app/_workspace/runs/'
      path: '/runs'
      fullPath: '/app/runs/'
      preLoaderRoute: typeof AuthenticatedAppWorkspaceRunsIndexRouteImport
      parentRoute: typeof AuthenticatedAppWorkspaceRouteRoute
    }
    '/_authenticated/app/_workspace/settings/': {
      id: '/_authenticated/app/_workspace/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AuthenticatedAppWorkspaceSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAppWorkspaceRouteRoute
    }
    '/_authenticated/app/_workspace/tasks/': {
      id: '/_authenticated/app/_workspace/tasks/'
      path: '/tasks'
      fullPath: '/app/tasks/'
      preLoaderRoute: typeof AuthenticatedAppWorkspaceTasksIndexRouteImport
      parentRoute: typeof AuthenticatedAppWorkspaceRouteRoute
    }
    '/_authenticated/app/_workspace/tasks/$taskId': {
      id: '/_authenticated/app/_workspace/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/app/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedAppWorkspaceTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedAppWorkspaceRouteRoute
    }
    '/_authenticated/app/_workspace/tasks/new': {
      id: '/_authenticated/app/_workspace/tasks/new'
      path: '/tasks/new'
      fullPath: '/app/tasks/new'
      preLoaderRoute: typeof AuthenticatedAppWorkspaceTasksNewRouteImport
      parentRoute: typeof AuthenticatedAppWorkspaceRouteRoute
    }
  }
}

interface AuthenticatedAppWorkspaceRouteRouteChildren {
  AuthenticatedAppWorkspaceTasksTaskIdRoute: typeof AuthenticatedAppWorkspaceTasksTaskIdRoute
  AuthenticatedAppWorkspaceTasksNewRoute: typeof AuthenticatedAppWorkspaceTasksNewRoute
  AuthenticatedAppWorkspaceApprovalsIndexRoute: typeof AuthenticatedAppWorkspaceApprovalsIndexRoute
  AuthenticatedAppWorkspaceDashboardIndexRoute: typeof AuthenticatedAppWorkspaceDashboardIndexRoute
  AuthenticatedAppWorkspaceIntegrationsIndexRoute: typeof AuthenticatedAppWorkspaceIntegrationsIndexRoute
  AuthenticatedAppWorkspaceProjectsIndexRoute: typeof AuthenticatedAppWorkspaceProjectsIndexRoute
  AuthenticatedAppWorkspaceRunsIndexRoute: typeof AuthenticatedAppWorkspaceRunsIndexRoute
  AuthenticatedAppWorkspaceSettingsIndexRoute: typeof AuthenticatedAppWorkspaceSettingsIndexRoute
  AuthenticatedAppWorkspaceTasksIndexRoute: typeof AuthenticatedAppWorkspaceTasksIndexRoute
}

const AuthenticatedAppWorkspaceRouteRouteChildren: AuthenticatedAppWorkspaceRouteRouteChildren =
  {
    AuthenticatedAppWorkspaceTasksTaskIdRoute:
      AuthenticatedAppWorkspaceTasksTaskIdRoute,
    AuthenticatedAppWorkspaceTasksNewRoute:
      AuthenticatedAppWorkspaceTasksNewRoute,
    AuthenticatedAppWorkspaceApprovalsIndexRoute:
      AuthenticatedAppWorkspaceApprovalsIndexRoute,
    AuthenticatedAppWorkspaceDashboardIndexRoute:
      AuthenticatedAppWorkspaceDashboardIndexRoute,
    AuthenticatedAppWorkspaceIntegrationsIndexRoute:
      AuthenticatedAppWorkspaceIntegrationsIndexRoute,
    AuthenticatedAppWorkspaceProjectsIndexRoute:
      AuthenticatedAppWorkspaceProjectsIndexRoute,
    AuthenticatedAppWorkspaceRunsIndexRoute:
      AuthenticatedAppWorkspaceRunsIndexRoute,
    AuthenticatedAppWorkspaceSettingsIndexRoute:
      AuthenticatedAppWorkspaceSettingsIndexRoute,
    AuthenticatedAppWorkspaceTasksIndexRoute:
      AuthenticatedAppWorkspaceTasksIndexRoute,
  }

const AuthenticatedAppWorkspaceRouteRouteWithChildren =
  AuthenticatedAppWorkspaceRouteRoute._addFileChildren(
    AuthenticatedAppWorkspaceRouteRouteChildren,
  )

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppWorkspaceRouteRoute: typeof AuthenticatedAppWorkspaceRouteRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppWorkspaceRouteRoute:
    AuthenticatedAppWorkspaceRouteRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthForgotPasswordRouteChildren {
  AuthForgotPasswordSentRoute: typeof AuthForgotPasswordSentRoute
}

const AuthForgotPasswordRouteChildren: AuthForgotPasswordRouteChildren = {
  AuthForgotPasswordSentRoute: AuthForgotPasswordSentRoute,
}

const AuthForgotPasswordRouteWithChildren =
  AuthForgotPasswordRoute._addFileChildren(AuthForgotPasswordRouteChildren)

interface AuthResetPasswordRouteChildren {
  AuthResetPasswordSuccessRoute: typeof AuthResetPasswordSuccessRoute
}

const AuthResetPasswordRouteChildren: AuthResetPasswordRouteChildren = {
  AuthResetPasswordSuccessRoute: AuthResetPasswordSuccessRoute,
}

const AuthResetPasswordRouteWithChildren =
  AuthResetPasswordRoute._addFileChildren(AuthResetPasswordRouteChildren)

interface AuthRouteRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRouteWithChildren
  AuthResetPasswordRoute: typeof AuthResetPasswordRouteWithChildren
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRouteWithChildren,
  AuthResetPasswordRoute: AuthResetPasswordRouteWithChildren,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CookiesRoute: CookiesRoute,
  DocsRoute: DocsRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
