/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthForgotPasswordSentRouteImport } from './routes/auth/forgot-password.sent'
import { Route as AuthResetPasswordSuccessRouteImport } from './routes/auth/reset-password.success'
import { Route as AuthenticatedAppApprovalsIndexRouteImport } from './routes/_authenticated/app/approvals/index'
import { Route as AuthenticatedAppIntegrationsIndexRouteImport } from './routes/_authenticated/app/integrations/index'
import { Route as AuthenticatedAppProjectsIndexRouteImport } from './routes/_authenticated/app/projects/index'
import { Route as AuthenticatedAppRunsIndexRouteImport } from './routes/_authenticated/app/runs/index'
import { Route as AuthenticatedAppSettingsIndexRouteImport } from './routes/_authenticated/app/settings/index'
import { Route as AuthenticatedAppTasksIndexRouteImport } from './routes/_authenticated/app/tasks/index'
import { Route as AuthenticatedAppTasksTaskIdRouteImport } from './routes/_authenticated/app/tasks/$taskId'
import { Route as AuthenticatedAppTasksNewRouteImport } from './routes/_authenticated/app/tasks/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthForgotPasswordSentRoute = AuthForgotPasswordSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => AuthForgotPasswordRoute,
} as any)
const AuthResetPasswordSuccessRoute =
  AuthResetPasswordSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => AuthResetPasswordRoute,
  } as any)
const AuthenticatedAppApprovalsIndexRoute =
  AuthenticatedAppApprovalsIndexRouteImport.update({
    id: '/approvals/',
    path: '/approvals/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppIntegrationsIndexRoute =
  AuthenticatedAppIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsIndexRoute =
  AuthenticatedAppProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppRunsIndexRoute =
  AuthenticatedAppRunsIndexRouteImport.update({
    id: '/runs/',
    path: '/runs/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSettingsIndexRoute =
  AuthenticatedAppSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppTasksIndexRoute =
  AuthenticatedAppTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppTasksTaskIdRoute =
  AuthenticatedAppTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppTasksNewRoute =
  AuthenticatedAppTasksNewRouteImport.update({
    id: '/tasks/new',
    path: '/tasks/new',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRouteWithChildren
  '/auth/reset-password': typeof AuthResetPasswordRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/': typeof AuthIndexRoute
  '/auth/forgot-password/sent': typeof AuthForgotPasswordSentRoute
  '/auth/reset-password/success': typeof AuthResetPasswordSuccessRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/tasks/$taskId': typeof AuthenticatedAppTasksTaskIdRoute
  '/app/tasks/new': typeof AuthenticatedAppTasksNewRoute
  '/app/approvals/': typeof AuthenticatedAppApprovalsIndexRoute
  '/app/integrations/': typeof AuthenticatedAppIntegrationsIndexRoute
  '/app/projects/': typeof AuthenticatedAppProjectsIndexRoute
  '/app/runs/': typeof AuthenticatedAppRunsIndexRoute
  '/app/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/app/tasks/': typeof AuthenticatedAppTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRouteWithChildren
  '/auth/reset-password': typeof AuthResetPasswordRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth': typeof AuthIndexRoute
  '/auth/forgot-password/sent': typeof AuthForgotPasswordSentRoute
  '/auth/reset-password/success': typeof AuthResetPasswordSuccessRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/tasks/$taskId': typeof AuthenticatedAppTasksTaskIdRoute
  '/app/tasks/new': typeof AuthenticatedAppTasksNewRoute
  '/app/approvals': typeof AuthenticatedAppApprovalsIndexRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsIndexRoute
  '/app/projects': typeof AuthenticatedAppProjectsIndexRoute
  '/app/runs': typeof AuthenticatedAppRunsIndexRoute
  '/app/settings': typeof AuthenticatedAppSettingsIndexRoute
  '/app/tasks': typeof AuthenticatedAppTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRouteWithChildren
  '/auth/reset-password': typeof AuthResetPasswordRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/': typeof AuthIndexRoute
  '/auth/forgot-password/sent': typeof AuthForgotPasswordSentRoute
  '/auth/reset-password/success': typeof AuthResetPasswordSuccessRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/tasks/$taskId': typeof AuthenticatedAppTasksTaskIdRoute
  '/_authenticated/app/tasks/new': typeof AuthenticatedAppTasksNewRoute
  '/_authenticated/app/approvals/': typeof AuthenticatedAppApprovalsIndexRoute
  '/_authenticated/app/integrations/': typeof AuthenticatedAppIntegrationsIndexRoute
  '/_authenticated/app/projects/': typeof AuthenticatedAppProjectsIndexRoute
  '/_authenticated/app/runs/': typeof AuthenticatedAppRunsIndexRoute
  '/_authenticated/app/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/_authenticated/app/tasks/': typeof AuthenticatedAppTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/docs'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/app'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-up'
    | '/auth/'
    | '/auth/forgot-password/sent'
    | '/auth/reset-password/success'
    | '/app/'
    | '/app/tasks/$taskId'
    | '/app/tasks/new'
    | '/app/approvals/'
    | '/app/integrations/'
    | '/app/projects/'
    | '/app/runs/'
    | '/app/settings/'
    | '/app/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-up'
    | '/auth'
    | '/auth/forgot-password/sent'
    | '/auth/reset-password/success'
    | '/app'
    | '/app/tasks/$taskId'
    | '/app/tasks/new'
    | '/app/approvals'
    | '/app/integrations'
    | '/app/projects'
    | '/app/runs'
    | '/app/settings'
    | '/app/tasks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/docs'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/app'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-up'
    | '/auth/'
    | '/auth/forgot-password/sent'
    | '/auth/reset-password/success'
    | '/_authenticated/app/'
    | '/_authenticated/app/tasks/$taskId'
    | '/_authenticated/app/tasks/new'
    | '/_authenticated/app/approvals/'
    | '/_authenticated/app/integrations/'
    | '/_authenticated/app/projects/'
    | '/_authenticated/app/runs/'
    | '/_authenticated/app/settings/'
    | '/_authenticated/app/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DocsRoute: typeof DocsRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/auth/forgot-password/sent': {
      id: '/auth/forgot-password/sent'
      path: '/sent'
      fullPath: '/auth/forgot-password/sent'
      preLoaderRoute: typeof AuthForgotPasswordSentRouteImport
      parentRoute: typeof AuthForgotPasswordRoute
    }
    '/auth/reset-password/success': {
      id: '/auth/reset-password/success'
      path: '/success'
      fullPath: '/auth/reset-password/success'
      preLoaderRoute: typeof AuthResetPasswordSuccessRouteImport
      parentRoute: typeof AuthResetPasswordRoute
    }
    '/_authenticated/app/approvals/': {
      id: '/_authenticated/app/approvals/'
      path: '/approvals'
      fullPath: '/app/approvals/'
      preLoaderRoute: typeof AuthenticatedAppApprovalsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/integrations/': {
      id: '/_authenticated/app/integrations/'
      path: '/integrations'
      fullPath: '/app/integrations/'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/projects/': {
      id: '/_authenticated/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AuthenticatedAppProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/runs/': {
      id: '/_authenticated/app/runs/'
      path: '/runs'
      fullPath: '/app/runs/'
      preLoaderRoute: typeof AuthenticatedAppRunsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings/': {
      id: '/_authenticated/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AuthenticatedAppSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/tasks/': {
      id: '/_authenticated/app/tasks/'
      path: '/tasks'
      fullPath: '/app/tasks/'
      preLoaderRoute: typeof AuthenticatedAppTasksIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/tasks/$taskId': {
      id: '/_authenticated/app/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/app/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedAppTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/tasks/new': {
      id: '/_authenticated/app/tasks/new'
      path: '/tasks/new'
      fullPath: '/app/tasks/new'
      preLoaderRoute: typeof AuthenticatedAppTasksNewRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppTasksTaskIdRoute: typeof AuthenticatedAppTasksTaskIdRoute
  AuthenticatedAppTasksNewRoute: typeof AuthenticatedAppTasksNewRoute
  AuthenticatedAppApprovalsIndexRoute: typeof AuthenticatedAppApprovalsIndexRoute
  AuthenticatedAppIntegrationsIndexRoute: typeof AuthenticatedAppIntegrationsIndexRoute
  AuthenticatedAppProjectsIndexRoute: typeof AuthenticatedAppProjectsIndexRoute
  AuthenticatedAppRunsIndexRoute: typeof AuthenticatedAppRunsIndexRoute
  AuthenticatedAppSettingsIndexRoute: typeof AuthenticatedAppSettingsIndexRoute
  AuthenticatedAppTasksIndexRoute: typeof AuthenticatedAppTasksIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppTasksTaskIdRoute: AuthenticatedAppTasksTaskIdRoute,
  AuthenticatedAppTasksNewRoute: AuthenticatedAppTasksNewRoute,
  AuthenticatedAppApprovalsIndexRoute: AuthenticatedAppApprovalsIndexRoute,
  AuthenticatedAppIntegrationsIndexRoute:
    AuthenticatedAppIntegrationsIndexRoute,
  AuthenticatedAppProjectsIndexRoute: AuthenticatedAppProjectsIndexRoute,
  AuthenticatedAppRunsIndexRoute: AuthenticatedAppRunsIndexRoute,
  AuthenticatedAppSettingsIndexRoute: AuthenticatedAppSettingsIndexRoute,
  AuthenticatedAppTasksIndexRoute: AuthenticatedAppTasksIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthForgotPasswordRouteChildren {
  AuthForgotPasswordSentRoute: typeof AuthForgotPasswordSentRoute
}

const AuthForgotPasswordRouteChildren: AuthForgotPasswordRouteChildren = {
  AuthForgotPasswordSentRoute: AuthForgotPasswordSentRoute,
}

const AuthForgotPasswordRouteWithChildren =
  AuthForgotPasswordRoute._addFileChildren(AuthForgotPasswordRouteChildren)

interface AuthResetPasswordRouteChildren {
  AuthResetPasswordSuccessRoute: typeof AuthResetPasswordSuccessRoute
}

const AuthResetPasswordRouteChildren: AuthResetPasswordRouteChildren = {
  AuthResetPasswordSuccessRoute: AuthResetPasswordSuccessRoute,
}

const AuthResetPasswordRouteWithChildren =
  AuthResetPasswordRoute._addFileChildren(AuthResetPasswordRouteChildren)

interface AuthRouteRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRouteWithChildren
  AuthResetPasswordRoute: typeof AuthResetPasswordRouteWithChildren
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRouteWithChildren,
  AuthResetPasswordRoute: AuthResetPasswordRouteWithChildren,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DocsRoute: DocsRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
